## Gold Layer

In [1]:
import pyodbc 
conn = pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    "Server=.\SQLEXPRESS;"
    "Database=Gravity_BookStore_DWH;"
    "Trusted_Connection=yes;"
)
cursor = conn.cursor()

In [2]:
import pandas as pd

In [3]:
df_Customer = pd.read_sql("SELECT * FROM silver.Customer" , con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_30912\3400879053.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Customer = pd.read_sql("SELECT * FROM silver.Customer" , con = conn)

In [5]:
df_Book = pd.read_sql("SELECT * FROM silver.Book" , con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_30912\2897424222.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Book = pd.read_sql("SELECT * FROM silver.Book" , con = conn)

In [6]:
df_Author_Book = pd.read_sql("SELECT * FROM silver.Author_Book" , con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_30912\1014377233.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Author_Book = pd.read_sql("SELECT * FROM silver.Author_Book" , con = conn)

In [20]:
df_Author = pd.read_sql("SELECT * FROM silver.Author" , con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_30912\2123806961.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Author = pd.read_sql("SELECT * FROM silver.Author" , con = conn)

In [25]:
df_Category = pd.read_sql("SELECT * FROM silver.Category" , con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_30912\3862610123.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Category = pd.read_sql("SELECT * FROM silver.Category" , con = conn)

In [46]:
df_Ordering = pd.read_sql("SELECT * FROM silver.Ordering " , con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_30912\3047065155.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Ordering = pd.read_sql("SELECT * FROM silver.Ordering " , con = conn)

In [56]:
df_Author = pd.read_sql("SELECT * FROM silver.Author " , con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_30912\4161754108.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Author = pd.read_sql("SELECT * FROM silver.Author " , con = conn)

In [9]:
df_Customer.columns

Index(['CustomerID', 'FirstName', 'LastName', 'ZipCode', 'City', 'State',
       'FullName'],
      dtype='str')

In [12]:
df_Customer['FullName'] = df_Customer['FirstName'] + ' ' + df_Customer['LastName']
df_Customer['CustomerSegment'] = range(1, len(df_Customer) + 1)

In [13]:
df_Customer = df_Customer[['CustomerSegment','FirstName' , 'LastName' , 'FullName' , 'City', 'State']]

In [15]:
df_Customer.head(5)

   CustomerSegment FirstName    LastName       FullName        City  State
0                1                                       Alexandria  Egypt
1                2            Abdel-Nabi     Abdel-Nabi  Alexandria  Egypt
2                3      Sara      Hassan    Sara Hassan  Alexandria  Egypt
3                4      Dina                     Dina    Alexandria  Egypt
4                5       Ali   El-Sharif  Ali El-Sharif       Aswan  Egypt

In [17]:
df_Book.columns

Index(['BookID', 'CategoryID', 'Title', 'ISBN', 'Year', 'Price', 'NoPages',
       'BookDescription'],
      dtype='str')

In [18]:
df_Author_Book.columns

Index(['AuthorID', 'BookID'], dtype='str')

In [21]:
df_Author.columns

Index(['AuthorID', 'AuthorName'], dtype='str')

In [26]:
df_Category.columns

Index(['CategoryID', 'CategoryDescription'], dtype='str')

In [22]:
df_ba = df_Book.merge(df_Author_Book , on = 'BookID' , how = 'inner')

In [23]:
df_baf = df_ba.merge(df_Author , on = 'AuthorID' , how = 'inner')

In [27]:
df_bafc = df_baf.merge(df_Category , on = 'CategoryID' , how = 'inner')

In [35]:
df_bafc['Price'].median()

np.float64(151.86)

In [ ]:
df_bafc['PriceRange'] = df_bafc['Price'].median()
df_bafc['PriceRange'] = df_bafc['Price'].median()

In [37]:
df_bafc.columns

Index(['BookID', 'CategoryID', 'Title', 'ISBN', 'Year', 'Price', 'NoPages',
       'BookDescription', 'AuthorID', 'AuthorName', 'CategoryDescription',
       'PriceRange'],
      dtype='str')

In [39]:
df_Book = df_bafc[['Title', 'ISBN' , 'AuthorName' ,'CategoryDescription' , 'Price' ,'Year' , 'PriceRange' ]]

In [41]:
df_Book.head(5)

,Title,ISBN,AuthorName,CategoryDescription,Price,Year,PriceRange
0,History of Egypt 56,978-977-979-110-7,Mohamed El-Sawy,History,162.42,2008,151.86
1,History of Egypt 56,978-977-979-110-7,Mohamed Afifi Matar,History,162.42,2008,151.86
2,Egyptian Law 112,978-977-797-195-8,Mohamed Abdel Wahab,Law,97.85,2021,151.86
3,Egyptian Law 112,978-977-797-195-8,Mohamed Ibrahim Mabrouk,Law,97.85,2021,151.86
4,Egyptian Law 112,978-977-797-195-8,Fekry Abaza,Law,97.85,2021,151.86

In [44]:
df_bafc['SalesID'] = range(1, len(df_bafc) + 1)

In [48]:
df_bafco = df_bafc.merge(df_Ordering , on = 'BookID' , how = 'inner')

In [47]:
df_Ordering.columns

Index(['OrderID', 'BookID', 'Price', 'Quantity'], dtype='str')

In [63]:
df_bafco['Total_Amount'] = df_bafco['Quantity'] * df_bafco['Price_x']

In [64]:
df_bafco.columns

Index(['BookID', 'CategoryID', 'Title', 'ISBN', 'Year', 'Price_x', 'NoPages',
       'BookDescription', 'AuthorID', 'AuthorName', 'CategoryDescription',
       'PriceRange', 'SalesID', 'OrderID', 'Price_y', 'Quantity',
       'Total Amount', 'Total_Amount'],
      dtype='str')

In [65]:
df_Sales = df_bafco[['SalesID','BookID','AuthorID' ,'Quantity','Price_x' , 'Total_Amount']]

In [66]:
df_Sales.head(5)

   SalesID BookID AuthorID  Quantity  Price_x  Total_Amount
0        1     56       86         1   162.42        162.42
1        1     56       86         2   162.42        324.84
2        1     56       86         3   162.42        487.26
3        1     56       86         3   162.42        487.26
4        1     56       86         1   162.42        162.42

In [67]:
df_Sales.dtypes

SalesID           int64
BookID              str
AuthorID            str
Quantity          int64
Price_x         float64
Total_Amount    float64
dtype: object

In [69]:
Sales = list(df_Sales.itertuples(index=None , name=None))

In [73]:
cursor.executemany("insert into gold.Sales values (?,?,?,?,?,?)" , Sales)
cursor.commit()

In [60]:
df_Book.dtypes

Title                      str
ISBN                       str
AuthorName                 str
CategoryDescription        str
Price                  float64
Year                       str
PriceRange             float64
dtype: object

In [74]:
Book = list(df_Book.itertuples(index=None , name=None))

In [75]:
cursor.executemany("insert into gold.Book values (?,?,?,?,?,?,?)" , Book)
cursor.commit()

In [61]:
df_Customer.dtypes

CustomerSegment    int64
FirstName            str
LastName             str
FullName             str
City                 str
State                str
dtype: object

In [77]:
Customer = list(df_Customer.itertuples(index=None , name=None))

In [78]:
cursor.executemany("insert into gold.Customer values (?,?,?,?,?,?)" , Customer)
cursor.commit()

In [62]:
df_Author.dtypes

AuthorID      str
AuthorName    str
dtype: object

In [80]:
Author = list(df_Author.itertuples(index=None , name=None))

In [81]:
cursor.executemany("insert into gold.Author values (?,?)" , Author)
cursor.commit()

In [82]:
cursor.close()
conn.close()