## Data Ingestion

In [30]:
import pandas as pd 

with open ('Dataset/Author_Book.csv' , 'r') as f :
    Author_Book= pd.read_csv(f)
Author_Book

      AuthorID  BookID
0            1       5
1            1      31
2            1      43
3            1     152
4            1     215
...        ...     ...
2954       100     799
2955       100     845
2956       100     857
2957       100     968
2958       100     970

[2959 rows x 2 columns]

In [31]:
df_Author_Book = pd.DataFrame(Author_Book)
df_Author_Book.head(5)

   AuthorID  BookID
0         1       5
1         1      31
2         1      43
3         1     152
4         1     215

In [32]:
with open ('Dataset/Author.csv' , 'r') as f :
    Author= pd.read_csv(f)
Author

    AuthorID              AuthorName
0          1          Naguib Mahfouz
1          2           Youssef Idris
2          3            Taha Hussein
3          4          Abbas Al-Aqqad
4          5         Tawfiq Al-Hakim
..       ...                     ...
95        96       Mahmoud El-Tohamy
96        97      Mohamed El-Helbawy
97        98  Abdel Rahman El-Shafei
98        99          Ahmed El-Masry
99       100        Mohamed El-Banna

[100 rows x 2 columns]

In [33]:
df_Author = pd.DataFrame(Author)
df_Author.head(5)

   AuthorID       AuthorName
0         1   Naguib Mahfouz
1         2    Youssef Idris
2         3     Taha Hussein
3         4   Abbas Al-Aqqad
4         5  Tawfiq Al-Hakim

In [34]:
with open ('Dataset/Book_Order.csv' , 'r') as f :
    Book_Order= pd.read_csv(f)
Book_Order

      OrderID  CustomerID   OrderDate
0           1         NaN  2020-12-17
1           2       379.0  2020-03-03
2           3       696.0  2020-07-05
3           4      1956.0  2023-05-28
4           5       508.0  2023-10-10
...       ...         ...         ...
7995     7996         NaN  2020-07-29
7996     7997        53.0  2023-01-28
7997     7998      1693.0  2020-11-14
7998     7999       790.0  2021-05-11
7999     8000       713.0  2022-03-15

[8000 rows x 3 columns]

In [ ]:
df_Book_Order = pd.DataFrame(Book_Order)
df_Book_Order = df_Book_Order.astype(object).where(pd.notna(df_Book_Order), None)

In [65]:
df_Book_Order.head(5)

   0       1           2
0  1    None  2020-12-17
1  2   379.0  2020-03-03
2  3   696.0  2020-07-05
3  4  1956.0  2023-05-28
4  5   508.0  2023-10-10

In [36]:
with open ('Dataset/Book.csv' , 'r') as f :
    Book = pd.read_csv(f)
Book

,BookID,CategoryID,Title,ISBN,Year,Price,NoPages,BookDescription
0,1,17,Chemistry Today 1,978-977-687-980-2,2001,72.66,725,This is a fascinating book about chemistry in ...
1,2,3,Islamic Studies 2,978-977-645-938-8,2004,80.34,630,This is a fascinating book about religious stu...
2,3,13,Egyptian Law 3,978-977-727-860-1,2011,132.41,277,This is a fascinating book about legal system ...
3,4,20,Sports in Egypt 4,978-977-181-749-5,2020,102.01,538,This is a fascinating book about sports and at...
4,5,18,Geography of Egypt 5,978-977-128-830-1,2010,165.12,586,This is a fascinating book about geography of ...
...,...,...,...,...,...,...,...,...
995,996,17,Chemistry Today 996,978-977-951-219-2,2001,196.78,517,This is a fascinating book about chemistry in ...
996,997,8,Economy of Egypt 997,978-977-696-246-1,2017,75.45,671,This is a fascinating book about economic deve...
997,998,13,Egyptian Law 998,978-977-136-332-9,2007,168.56,115,This is a fascinating book about legal system ...
998,999,9,Political Analysis 999,978-977-983-446-3,2021,66.50,432,This is a fascinating book about political lan...
999,1000,16,Physics Explained 1000,978-977-244-192-7,2014,133.67,184,This is a fascinating book about physics and a...

In [ ]:
df_Book = pd.DataFrame(Book)
df_Book.head(5)

,BookID,CategoryID,Title,ISBN,Year,Price,NoPages,BookDescription
0,1,17,Chemistry Today 1,978-977-687-980-2,2001,72.66,725,This is a fascinating book about chemistry in ...
1,2,3,Islamic Studies 2,978-977-645-938-8,2004,80.34,630,This is a fascinating book about religious stu...
2,3,13,Egyptian Law 3,978-977-727-860-1,2011,132.41,277,This is a fascinating book about legal system ...
3,4,20,Sports in Egypt 4,978-977-181-749-5,2020,102.01,538,This is a fascinating book about sports and at...
4,5,18,Geography of Egypt 5,978-977-128-830-1,2010,165.12,586,This is a fascinating book about geography of ...

In [38]:
df_Book.columns

Index(['BookID', 'CategoryID', 'Title', 'ISBN', 'Year', 'Price', 'NoPages',
       'BookDescription'],
      dtype='str')

In [39]:
with open ('Dataset/Category.csv' , 'r') as f :
   Category = pd.read_csv(f)
Category

    CategoryID CategoryDescription
0            1          Literature
1            2             History
2            3            Religion
3            4             Science
4            5            Children
5            6          Philosophy
6            7                 Art
7            8           Economics
8            9            Politics
9           10              Health
10          11         Engineering
11          12            Medicine
12          13                 Law
13          14         Agriculture
14          15         Mathematics
15          16             Physics
16          17           Chemistry
17          18           Geography
18          19              Travel
19          20              Sports

In [40]:
df_Category = pd.DataFrame(Category)
df_Category.head(5)

   CategoryID CategoryDescription
0           1          Literature
1           2             History
2           3            Religion
3           4             Science
4           5            Children

In [81]:
with open ('Dataset/Customer.csv' , 'r') as f :
    Customer= pd.read_csv(f)
Customer

      CustomerID FirstName    LastName  ZipCode            City  State
0              1       NaN      Shaker    70902             NaN  Egypt
1              2       NaN    El-Gamal    41987             NaN  Egypt
2              3     Asmaa         NaN    62957           Tanta  Egypt
3              4     Rania         NaN    17634            Giza  Egypt
4              5      Nour     Ibrahim    87592             NaN  Egypt
...          ...       ...         ...      ...             ...    ...
1995        1996      Sara      Hassan    39585             NaN  Egypt
1996        1997       NaN         NaN    50438             NaN  Egypt
1997        1998       NaN   El-Naggar    24341             NaN  Egypt
1998        1999       NaN         NaN    11133             NaN  Egypt
1999        2000    Khaled  Abdel-Aziz    95912  Kafr El-Sheikh  Egypt

[2000 rows x 6 columns]

In [83]:
df_Customer = pd.DataFrame(Customer)
df_Customer = Customer.astype(object).where(pd.notna(Customer), None)
df_Customer.head(5)

  CustomerID FirstName  LastName ZipCode   City  State
0          1      None    Shaker   70902   None  Egypt
1          2      None  El-Gamal   41987   None  Egypt
2          3     Asmaa      None   62957  Tanta  Egypt
3          4     Rania      None   17634   Giza  Egypt
4          5      Nour   Ibrahim   87592   None  Egypt

In [43]:
with open ('Dataset/Ordering.csv' , 'r') as f :
    Ordering= pd.read_csv(f)
Ordering

       OrderID  BookID   Price  Quantity
0            1     198  180.70       1.0
1            1     256  114.14       2.0
2            1     393  188.30       1.0
3            1     492  218.49       1.0
4            1     996     NaN       1.0
...        ...     ...     ...       ...
32029     7999     910  142.16       2.0
32030     7999     951   81.40       NaN
32031     8000      49  237.53       2.0
32032     8000     217   78.51       1.0
32033     8000     876  227.05       3.0

[32034 rows x 4 columns]

In [88]:
df_Ordering = pd.DataFrame(Ordering)
df_Ordering = df_Ordering.astype(object).where(pd.notna(df_Ordering), None)
df_Ordering.head(5)

   0    1       2    3
0  1  198   180.7  1.0
1  1  256  114.14  2.0
2  1  393   188.3  1.0
3  1  492  218.49  1.0
4  1  996    None  1.0

## Bronze Layer

In [45]:
import pyodbc 
conn = pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    "Server=.\SQLEXPRESS;"
    "Database=Gravity_BookStore_DWH;"
    "Trusted_Connection=yes;"
)
cursor = conn.cursor()

In [48]:
Author_Book = list (df_Author_Book.itertuples(index = None , name = None))

In [91]:
cursor.executemany('insert into bronze.Author_Book values (? , ?)' , Author_Book )
conn.commit()

In [ ]:
Author = list (df_Author.itertuples(index = None , name = None))

In [92]:
cursor.executemany('insert into bronze.Author values (? , ?)' , Author )
conn.commit()

In [66]:
Book_Order = list (df_Book_Order.itertuples(index = None , name = None))

In [93]:
cursor.executemany('insert into bronze.Book_Order values (? , ? , ?)' , Book_Order )
conn.commit()

In [70]:
Book = list (df_Book.itertuples(index = None , name = None))

In [94]:
cursor.executemany('insert into bronze.Book values (? , ? , ? , ? , ? , ? , ? , ?)' , Book )
conn.commit()

In [52]:
Category =  list (df_Category.itertuples(index = None , name = None))

In [95]:
cursor.executemany('insert into bronze.Category values (? , ?)' , Category )
conn.commit()

In [ ]:
Customer =  list (df_Customer.itertuples(index = None , name = None))

In [96]:
cursor.executemany('insert into bronze.Customer values (? , ? , ? , ? , ? , ?)' , Customer )
conn.commit()

In [89]:
Ordering =  list (df_Ordering.itertuples(index = None , name = None))

In [97]:
cursor.executemany('insert into bronze.Ordering values (? , ? , ? , ?)' , Ordering )
conn.commit()

In [98]:
cursor.close()
conn.close()