## Silver Layer

In [72]:
import pyodbc 
conn = pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    "Server=.\SQLEXPRESS;"
    "Database=Gravity_BookStore_DWH;"
    "Trusted_Connection=yes;"
)
cursor = conn.cursor()

In [75]:
cursor.close()
conn.close()

In [21]:
import pandas as pd

In [7]:
df_Author_Book = pd.read_sql("SELECT * FROM bronze.Author_Book" , con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_25788\3402471078.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Author_Book = pd.read_sql("SELECT * FROM bronze.Author_Book" , con = conn)

In [8]:
df_Author = pd.read_sql("SELECT * FROM bronze.Author", con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_25788\2944197904.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Author = pd.read_sql("SELECT * FROM bronze.Author", con = conn)

In [9]:
df_Book_Order = pd.read_sql("SELECT * FROM bronze.Book_Order", con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_25788\2617749810.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Book_Order = pd.read_sql("SELECT * FROM bronze.Book_Order", con = conn)

In [10]:
df_Book = pd.read_sql("SELECT * FROM bronze.Book", con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_25788\2880972814.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Book = pd.read_sql("SELECT * FROM bronze.Book", con = conn)

In [11]:
df_Category = pd.read_sql("SELECT * FROM bronze.Category", con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_25788\3244967066.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Category = pd.read_sql("SELECT * FROM bronze.Category", con = conn)

In [12]:
df_Customer = pd.read_sql("SELECT * FROM bronze.Customer", con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_25788\2665588764.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Customer = pd.read_sql("SELECT * FROM bronze.Customer", con = conn)

In [13]:
df_Ordering = pd.read_sql("SELECT * FROM bronze.Ordering", con = conn)

C:\Users\Anas\AppData\Local\Temp\ipykernel_25788\514521829.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Ordering = pd.read_sql("SELECT * FROM bronze.Ordering", con = conn)

In [17]:
df_Book.head(5)

,BookID,CategoryID,Title,ISBN,Year,Price,NoPages,BookDescription
0,56,2,History of Egypt 56,978-977-979-110-7,2008,162.42,728,This is a fascinating book about ancient and m...
1,112,13,Egyptian Law 112,978-977-797-195-8,2021,97.85,461,This is a fascinating book about legal system ...
2,167,7,Egyptian Art 167,978-977-396-489-2,2021,56.81,962,This is a fascinating book about Egyptian art ...
3,168,5,Children Stories 168,978-977-597-838-9,2022,62.42,436,This is a fascinating book about children educ...
4,169,8,Economy of Egypt 169,978-977-504-354-5,2004,116.7,239,This is a fascinating book about economic deve...

In [22]:
df_Author_Book.isnull().sum()

AuthorID    0
BookID      0
dtype: int64

In [23]:
df_Author.isnull().sum()

AuthorID      0
AuthorName    0
dtype: int64

In [93]:
df_Book.isnull().sum()

BookID             0
CategoryID         0
Title              0
ISBN               0
Year               0
Price              0
NoPages            0
BookDescription    0
dtype: int64

In [96]:
df_Book['Price'] = df_Book['Price'].astype('float64')
df_Book['NoPages'] = df_Book['NoPages'].astype('Int64')

In [94]:
df_Book.dtypes

BookID                 str
CategoryID             str
Title                  str
ISBN                   str
Year                   str
Price              float64
NoPages              Int64
BookDescription        str
dtype: object

In [100]:
import numpy as np

In [101]:
df_Book = df_Book.map(
    lambda x: int(x) if isinstance(x, np.integer) else x
)

In [30]:
df_Customer.isnull().sum()

CustomerID      0
FirstName       0
LastName        0
ZipCode         0
City          872
State           0
dtype: int64

In [33]:
df_Customer['FirstName'] = df_Customer['FirstName'].fillna(' ')
df_Customer['LastName'] = df_Customer['LastName'].fillna(' ')
df_Customer['City'] = df_Customer['City'].fillna(df_Customer['City'].mode()[0])

In [34]:
df_Customer.isnull().sum()

CustomerID    0
FirstName     0
LastName      0
ZipCode       0
City          0
State         0
dtype: int64

In [35]:
df_Category.isnull().sum()

CategoryID             0
CategoryDescription    0
dtype: int64

In [36]:
df_Ordering.isnull().sum()

OrderID        0
BookID         0
Price       3240
Quantity    3022
dtype: int64

In [38]:
df_o_book = df_Book.merge(df_Ordering , on = 'BookID' , how = 'inner')

In [ ]:
df_o_book.isnull().sum()

BookID                0
CategoryID            0
Title                 0
ISBN                  0
Year                  0
Price_x               0
NoPages               0
BookDescription       0
OrderID               0
Price_y            3240
Quantity           3022
dtype: int64

In [53]:
df_o_book['Price_y'] = df_o_book['Price_y'].fillna(df_o_book['Price_x'])
df_o_book['Quantity'] = df_o_book['Quantity'].fillna(df_o_book['Quantity'].mode()[0])

In [54]:
df_o_book

,BookID,CategoryID,Title,ISBN,Year,Price_x,NoPages,BookDescription,OrderID,Price_y,Quantity
0,56,2,History of Egypt 56,978-977-979-110-7,2008,162.42,728,This is a fascinating book about ancient and m...,30,162.42,1
1,56,2,History of Egypt 56,978-977-979-110-7,2008,162.42,728,This is a fascinating book about ancient and m...,290,162.42,2
2,56,2,History of Egypt 56,978-977-979-110-7,2008,162.42,728,This is a fascinating book about ancient and m...,429,162.42,3
3,56,2,History of Egypt 56,978-977-979-110-7,2008,162.42,728,This is a fascinating book about ancient and m...,472,162.42,3
4,56,2,History of Egypt 56,978-977-979-110-7,2008,162.42,728,This is a fascinating book about ancient and m...,518,162.42,1
...,...,...,...,...,...,...,...,...,...,...,...
64063,1000,16,Physics Explained 1000,978-977-244-192-7,2014,133.67,184,This is a fascinating book about physics and a...,4805,133.67,3
64064,1000,16,Physics Explained 1000,978-977-244-192-7,2014,133.67,184,This is a fascinating book about physics and a...,5194,133.67,3
64065,1000,16,Physics Explained 1000,978-977-244-192-7,2014,133.67,184,This is a fascinating book about physics and a...,5554,133.67,1
64066,1000,16,Physics Explained 1000,978-977-244-192-7,2014,133.67,184,This is a fascinating book about physics and a...,6589,133.67,1
64067,1000,16,Physics Explained 1000,978-977-244-192-7,2014,133.67,184,This is a fascinating book about physics and a...,7968,133.67,2

In [55]:
df_Ordering = df_o_book[['OrderID','BookID','Price_x','Quantity']]

In [56]:
df_Ordering.isnull().sum()

OrderID     0
BookID      0
Price_x     0
Quantity    0
dtype: int64

In [ ]:
df_Ordering['Price_x'] = df_Ordering['Price_x'].astype('Float64')
df_Ordering['Quantity'] = df_Ordering['Quantity'].astype('Int64')

In [71]:
df_Ordering.dtypes

OrderID         str
BookID          str
Price_x     Float64
Quantity      Int64
dtype: object

In [59]:
df_Book_Order.isna().sum()

OrderID         0
CustomerID    349
OrderDate       0
dtype: int64

In [88]:
df_Book_Order['CustomerID'] = df_Book_Order['CustomerID'].fillna('0')

In [82]:
import pyodbc 
conn = pyodbc.connect(
    "Driver={ODBC Driver 17 for SQL Server};"
    "Server=.\SQLEXPRESS;"
    "Database=Gravity_BookStore_DWH;"
    "Trusted_Connection=yes;"
)
cursor = conn.cursor()

In [77]:
Author_Book = list (df_Author_Book.itertuples(index = None , name = None))

In [80]:
cursor.executemany('insert into silver.Author_Book values (? , ?)' , Author_Book )
conn.commit()

In [83]:
Author = list (df_Author.itertuples(index = None , name = None))

In [84]:
cursor.executemany('insert into silver.Author values (? , ?)' , Author )
conn.commit()

In [89]:
Book_Order = list (df_Book_Order.itertuples(index = None , name = None))

In [90]:
cursor.executemany('insert into silver.Book_Order values (? , ? , ?)' , Book_Order )
conn.commit()

In [102]:
Book = list (df_Book.itertuples(index = None , name = None))

In [103]:
cursor.executemany('insert into silver.Book values (? , ? , ? , ? , ? , ? , ? , ?)' , Book )
conn.commit()

In [104]:
Category =  list (df_Category.itertuples(index = None , name = None))

In [105]:
cursor.executemany('insert into silver.Category values (? , ?)' , Category )
conn.commit()

In [106]:
Customer =  list (df_Customer.itertuples(index = None , name = None))

In [107]:
cursor.executemany('insert into silver.Customer values (? , ? , ? , ? , ? , ?)' , Customer )
conn.commit()

In [111]:
Ordering =  list (df_Ordering.itertuples(index = None , name = None))

In [110]:
df_Ordering = df_Ordering.map(
    lambda x: int(x) if isinstance(x, np.integer) else x
)

In [112]:
cursor.executemany('insert into silver.Ordering values (? , ? , ? , ?)' , Ordering )
conn.commit()

In [113]:
cursor.close()
conn.close()